# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
estep_calc <- function(data, z, mean, tau, sigma, psi, omega, gamma, det_sigma, det_psi) {
    .Call(`_sparsemixmat_estep_calc`, data, z, mean, tau, sigma, psi, omega, gamma, det_sigma, det_psi)
}

#' @export
mstep_obj <- function(data, z, mean, sigma, psi, omega, gamma, tau) {
    .Call(`_sparsemixmat_mstep_obj`, data, z, mean, sigma, psi, omega, gamma, tau)
}

#' @export
penalization_M_mat_coord_ascent <- function(data, data_cent, z, Nk, mu, omega, gamma, penalty_mu, p, q, N) {
    .Call(`_sparsemixmat_penalization_M_mat_coord_ascent`, data, data_cent, z, Nk, mu, omega, gamma, penalty_mu, p, q, N)
}

#' @export
mean_w_array <- function(data, z) {
    .Call(`_sparsemixmat_mean_w_array`, data, z)
}

#' @export
cov_w_array <- function(data, z, mean, inv, Nk, pbyp) {
    .Call(`_sparsemixmat_cov_w_array`, data, z, mean, inv, Nk, pbyp)
}

